'use client'
import{useState}from'react'
const SP:Record<string,{label:string;items:{text:string;badge?:string}[]}> = {desk:{label:'書桌整理清單',items:[{text:'清空桌面所有物品',badge:'必做'},{text:'分類文件文具雜物'},{text:'丟棄過期收據廢紙'},{text:'文具只留常用3支筆'},{text:'電線整理貼上標籤'},{text:'桌面只留今日必要物品'}]},wardrobe:{label:'衣櫃整理清單',items:[{text:'全部衣物取出攤開',badge:'必做'},{text:'依類型分堆上衣褲外套'},{text:'超過一年未穿考慮送出'},{text:'破損變形衣物直接淘汰'},{text:'常穿放前方少穿放後方'},{text:'折疊統一方式直立收納'}]},kitchen:{label:'廚房整理清單',items:[{text:'清查過期食品與調味料',badge:'必做'},{text:'餐具統計過多的送出'},{text:'常用鍋具放瓦斯爐旁'},{text:'塑膠袋只留10個'},{text:'清潔用品集中一區'},{text:'冰箱門背貼購物清單欄'}]},bathroom:{label:'浴室整理清單',items:[{text:'清查過期保養品藥品',badge:'必做'},{text:'只留1套備用備品'},{text:'毛巾超過3條斷捨離'},{text:'瓶瓶罐罐整理到收納架'},{text:'清除水垢黴菌'},{text:'放一個小香氛提升儀式感'}]},bag:{label:'包包整理清單',items:[{text:'倒出所有東西',badge:'必做'},{text:'丟棄發票廢紙屑'},{text:'零錢集中到錢包'},{text:'超過3個購物袋只留一個'},{text:'藥品確認是否過期'},{text:'常用物品分區放小包'}]},digital:{label:'數位整理清單',items:[{text:'截圖資料夾整理或刪除',badge:'必做'},{text:'手機App超過3頁刪一輪'},{text:'相簿備份到雲端'},{text:'訂閱email取消不需要的'},{text:'桌面資料夾分類命名'},{text:'清除瀏覽器書籤'}]}}
const PD=[{name:'PP收納盒大',brand:'無印良品',w:37,d:26,h:17,types:['shelf','drawer','wardrobe'],fit:'perfect'},{name:'PP收納盒中',brand:'無印良品',w:25,d:20,h:14,types:['shelf','drawer','wardrobe'],fit:'perfect'},{name:'SKUBB衣物整理盒',brand:'IKEA',w:44,d:55,h:19,types:['wardrobe','under'],fit:'perfect'},{name:'SAMLA透明收納箱',brand:'IKEA',w:57,d:39,h:28,types:['under','shelf'],fit:'perfect'},{name:'軟質整理盒6格',brand:'DAISO',w:32,d:22,h:10,types:['drawer'],fit:'perfect'},{name:'床下扁型收納盒',brand:'NITORI',w:74,d:40,h:14,types:['under'],fit:'perfect'},{name:'不織布衣物收納袋',brand:'NITORI',w:40,d:25,h:30,types:['wardrobe'],fit:'perfect'},{name:'桌面整理架竹製',brand:'誠品生活',w:28,d:18,h:22,types:['shelf'],fit:'perfect'},{name:'KUGGIS收納盒附蓋',brand:'IKEA',w:37,d:54,h:21,types:['shelf','wardrobe','under'],fit:'ok'},{name:'PP資料盒薄型',brand:'無印良品',w:10,d:32,h:24,types:['shelf','drawer'],fit:'ok'}]
const SI:Record<string,string>={desk:'🗂',wardrobe:'👕',kitchen:'🍳',bathroom:'🪥',bag:'👜',digital:'📱'}
const SN:Record<string,string>={desk:'書桌',wardrobe:'衣櫃',kitchen:'廚房',bathroom:'浴室',bag:'包包',digital:'數位'}
export default function Home(){
const[tab,setTab]=useState<'checklist'|'declutter'|'recommend'>('checklist')
const[space,setSpace]=useState('desk')
const[checked,setChecked]=useState<Record<string,boolean[]>>({})
const[items,setItems]=useState<{name:string;decision:string|null}[]>([])
const[input,setInput]=useState('')
const[mW,setMW]=useState('')
const[mD,setMD]=useState('')
const[mH,setMH]=useState('')
const[spaceType,setSpaceType]=useState('shelf')
const getC=()=>checked[space]||SP[space].items.map(()=>false)
const toggleC=(i:number)=>{const c=getC();const n=[...c];n[i]=!n[i];setChecked({...checked,[space]:n})}
const done=getC().filter(Boolean).length
const total=SP[space].items.length
const pct=total?Math.round((done/total)*100):0
const addItem=(name?:string)=>{const v=name||input.trim();if(!v)return;setItems([...items,{name:v,decision:null}]);setInput('')}
const setDec=(i:number,d:string)=>{const n=[...items];n[i].decision=n[i].decision===d?null:d;setItems(n)}
const prods=PD.filter(p=>{const w=parseFloat(mW),d=parseFloat(mD),h=parseFloat(mH);return p.types.includes(spaceType)&&(!mW||p.w<=w+5)&&(!mD||p.d<=d+5)&&(!mH||p.h<=h+5)}).slice(0,4)
const bg='#F5F0E8',ww='#FAF8F4',ink='#2C2820',sg='#7A9E8A',bd='#DDD8CF',ml='#6B6358',mf='#A39B8E',cr='#EDE8DD'
return(<div style={{minHeight:'100vh',background:bg,fontFamily:"'Noto Sans TC',sans-serif"}}>
<link href="https://fonts.googleapis.com/css2?family=Noto+Serif+TC:wght@700&family=Noto+Sans+TC:wght@300;400;500&display=swap" rel="stylesheet"/>
<nav style={{background:ww,borderBottom:`1px solid ${bd}`,padding:'0 24px',display:'flex',alignItems:'center',justifyContent:'space-between',height:56,position:'sticky',top:0,zIndex:100}}>
<div style={{fontFamily:"'Noto Serif TC',serif",fontWeight:700,fontSize:17,color:ink}}>整理<span style={{color:sg}}>•</span>小幫手</div>
<div style={{display:'flex',gap:4}}>{(['checklist','declutter','recommend'] as const).map(t=>(<button key={t} onClick={()=>setTab(t)} style={{padding:'6px 16px',borderRadius:20,border:'none',background:tab===t?ink:'transparent',color:tab===t?ww:ml,fontSize:13,cursor:'pointer',fontWeight:tab===t?500:400}}>{t==='checklist'?'整理清單':t==='declutter'?'斷捨離':'收納推薦'}</button>))}</div>
</nav>
<div style={{padding:'32px 24px',maxWidth:760,margin:'0 auto'}}>
{tab==='checklist'&&<><h1 style={{fontFamily:"'Noto Serif TC',serif",fontSize:26,fontWeight:700,marginBottom:6,color:ink}}>今天整理哪裡？</h1><p style={{color:ml,fontSize:14,marginBottom:28}}>選一個空間，開始今日的整理任務</p><div style={{display:'grid',gridTemplateColumns:'repeat(3,1fr)',gap:10,marginBottom:20}}>{Object.keys(SP).map(k=>(<button key={k} onClick={()=>setSpace(k)} style={{padding:'14px 10px',border:space===k?`2px solid ${sg}`:`1px solid ${bd}`,borderRadius:10,background:space===k?'#EAF2EE':ww,cursor:'pointer',textAlign:'center'}}><span style={{fontSize:22,display:'block',marginBottom:4}}>{SI[k]}</span><span style={{fontSize:13,color:ink}}>{SN[k]}</span></button>))}</div><div style={{background:ww,border:`1px solid ${bd}`,borderRadius:12,padding:'20px 24px'}}><div style={{fontSize:13,fontWeight:500,color:mf,textTransform:'uppercase',letterSpacing:'0.08em',marginBottom:14}}>{SP[space].label}</div>{SP[space].items.map((item,i)=>(<div key={i} onClick={()=>toggleC(i)} style={{display:'flex',alignItems:'center',gap:12,padding:'11px 0',borderBottom:i<total-1?`1px solid ${cr}`:'none',cursor:'pointer'}}><div style={{width:20,height:20,border:getC()[i]?'none':`1.5px solid ${bd}`,borderRadius:5,flexShrink:0,display:'flex',alignItems:'center',justifyContent:'center',background:getC()[i]?sg:'white'}}>{getC()[i]&&<svg width="10" height="7" viewBox="0 0 10 7" fill="none"><path d="M1 3.5L3.5 6L9 1" stroke="white" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round"/></svg>}</div><span style={{fontSize:14,flex:1,textDecoration:getC()[i]?'line-through':'none',color:getC()[i]?mf:ink}}>{item.text}</span>{item.badge&&<span style={{fontSize:11,padding:'2px 8px',borderRadius:10,background:'#F0E2C0',color:'#C4953A',fontWeight:500}}>{item.badge}</span>}</div>))}<div style={{background:cr,borderRadius:4,height:6,marginTop:16,overflow:'hidden'}}><div style={{height:'100%',borderRadius:4,background:sg,width:`${pct}%`,transition:'width 0.4s'}}/></div><div style={{fontSize:12,color:mf,marginTop:6,textAlign:'right'}}>{done} / {total} 完成</div></div></>}
{tab==='declutter'&&<><h1 style={{fontFamily:"'Noto Serif TC',serif",fontSize:26,fontWeight:700,marginBottom:6,color:ink}}>斷捨離決策</h1><p style={{color:ml,fontSize:14,marginBottom:28}}>逐一判斷每件物品的去留</p><div style={{background:ww,border:`1px solid ${bd}`,borderRadius:12,padding:'20px 24px',marginBottom:16}}><div style={{fontSize:13,fontWeight:500,color:mf,textTransform:'uppercase',letterSpacing:'0.08em',marginBottom:14}}>新增物品</div><div style={{display:'flex',gap:10,marginBottom:16}}><input style={{flex:1,border:`1px solid ${bd}`,borderRadius:8,padding:'10px 14px',fontSize:14,background:'white',color:ink,outline:'none'}} value={input} onChange={e=>setInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&addItem()} placeholder="例：三年沒穿的外套"/><button style={{padding:'10px 18px',borderRadius:8,border:'none',fontSize:14,cursor:'pointer',fontWeight:500,background:ink,color:'white'}} onClick={()=>addItem()}>加入</button></div><div style={{display:'flex',gap:8,flexWrap:'wrap',alignItems:'center'}}><span style={{fontSize:12,color:mf}}>快速加：</span>{['備用充電線','舊T-shirt','過期保養品','購物袋'].map(n=>(<button key={n} style={{padding:'5px 12px',borderRadius:6,border:'none',fontSize:12,cursor:'pointer',background:cr,color:ml}} onClick={()=>addItem(n)}>{n}</button>))}</div></div><div style={{background:ww,border:`1px solid ${bd}`,borderRadius:12,padding:'20px 24px'}}><div style={{fontSize:13,fontWeight:500,color:mf,textTransform:'uppercase',letterSpacing:'0.08em',marginBottom:14}}>等待判斷</div>{items.length===0?<div style={{textAlign:'center',padding:'28px 0',color:mf,fontSize:14}}>從上方加入第一件物品</div>:<>{items.map((item,i)=>(<div key={i} style={{display:'flex',alignItems:'center',justifyContent:'space-between',padding:'12px 0',borderBottom:`1px solid ${cr}`,gap:12}}><span style={{fontSize:14,flex:1,color:ink}}>{item.name}</span><div style={{display:'flex',gap:6}}>{(['keep','donate','toss'] as const).map(d=>{const ac=item.decision===d;const col=d==='keep'?sg:d==='donate'?'#C47B5A':mf;return<button key={d} onClick={()=>setDec(i,d)} style={{padding:'4px 12px',borderRadius:20,border:`1px solid ${col}`,background:ac?col:'white',color:ac?'white':col,fontSize:12,cursor:'pointer'}}>{d==='keep'?'留':d==='donate'?'送':'丟'}</button>})}</div></div>))}<div style={{display:'flex',gap:10,marginTop:16,flexWrap:'wrap'}}>{([['keep','留下','#EAF2EE',sg],['donate','送出','#F0D5C8','#C47B5A'],['toss','丟棄',cr,ml]] as const).map(([d,label,bg2,col])=>(<span key={d} style={{padding:'5px 14px',borderRadius:20,fontSize:13,fontWeight:500,background:bg2,color:col}}>{label} {items.filter(x=>x.decision===d).length}</span>))}</div></>}</div></>}
{tab==='recommend'&&<><h1 style={{fontFamily:"'Noto Serif TC',serif",fontSize:26,fontWeight:700,marginBottom:6,color:ink}}>收納品推薦</h1><p style={{color:ml,fontSize:14,marginBottom:28}}>輸入空間尺寸，找到適合的收納工具</p><div style={{background:ww,border:`1px solid ${bd}`,borderRadius:12,padding:'20px 24px',marginBottom:16}}><div style={{fontSize:13,fontWeight:500,color:mf,textTransform:'uppercase',letterSpacing:'0.08em',marginBottom:14}}>空間尺寸</div><select value={spaceType} onChange={e=>setSpaceType(e.target.value)} style={{width:'100%',border:`1px solid ${bd}`,borderRadius:8,padding:'10px 14px',fontSize:14,background:'white',color:ink,marginBottom:12,outline:'none'}}><option value="shelf">層架書架</option><option value="drawer">抽屜</option><option value="under">床底沙發下</option><option value="wardrobe">衣櫃內部</option></select><div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:12}}>{([['寬度',mW,setMW],['深度',mD,setMD],['高度',mH,setMH]] as [string,string,(v:string)=>void][]).map(([label,val,setter])=>(<div key={label}><div style={{fontSize:12,color:mf,marginBottom:5,fontWeight:500}}>{label}</div><input type="number" style={{width:'100%',border:`1px solid ${bd}`,borderRadius:8,padding:'10px 12px',fontSize:15,background:'white',color:ink,outline:'none',textAlign:'center'}} value={val} onChange={e=>setter(e.target.value)} placeholder="0"/><div style={{fontSize:12,color:mf,textAlign:'center',marginTop:4}}>公分</div></div>))}</div></div><div style={{background:ww,border:`1px solid ${bd}`,borderRadius:12,padding:'20px 24px'}}><div style={{fontSize:13,fontWeight:500,color:mf,textTransform:'uppercase',letterSpacing:'0.08em',marginBottom:14}}>推薦商品</div>{(!mW&&!mD&&!mH)?<div style={{textAlign:'center',padding:'28px 0',color:mf,fontSize:14}}>輸入尺寸後自動推薦</div>:prods.length===0?<div style={{textAlign:'center',padding:'28px 0',color:mf,fontSize:14}}>找不到符合商品</div>:<div style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:12}}>{prods.map((p,i)=>(<div key={i} style={{border:`1px solid ${bd}`,borderRadius:10,padding:'14px 16px',background:'white'}}><div style={{fontSize:14,fontWeight:500,marginBottom:4,color:ink}}>{p.name}</div><div style={{fontSize:11,color:mf,marginBottom:4,textAlign:'right'}}>{p.brand}</div><div style={{fontSize:12,color:ml,marginBottom:8}}>{p.w}x{p.d}x{p.h} cm</div><span style={{fontSize:11,padding:'3px 8px',borderRadius:8,background:p.fit==='perfect'?'#EAF2EE':'#F0E2C0',color:p.fit==='perfect'?sg:'#C4953A',fontWeight:500,display:'inline-block'}}>{p.fit==='perfect'?'完美符合':'可以使用'}</span></div>))}</div>}</div></>}
</div></div>)
}
